### ISSUE TITLE
Can we keep this branch as example

### ISSUE THREAD

**Issue by Jeroen-Notenbomer** [Sparker95/Project_0.Stratis#1]
Nice to see what needs to be added to add a new action/goal.

**Comment by Jeroen-Notenbomer** [comment]
I thought issues where branch related

**Comment by Sparker95** [comment]
Which branch did you mean anyway?

**Comment by Sparker95** [comment]
The grenadeAvoidance branch will be kept as an example of GOAP usage. It was an experiment anyway.
